// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.1
// source: beef/beef.proto

package beef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the file content.
type SummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_beef_beef_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beef_beef_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_beef_beef_proto_rawDescGZIP(), []int{0}
}

func (x *SummaryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// The response message containing the beef counting summary
type SummaryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Json string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *SummaryReply) Reset() {
	*x = SummaryReply{}
	mi := &file_beef_beef_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryReply) ProtoMessage() {}

func (x *SummaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_beef_beef_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryReply.ProtoReflect.Descriptor instead.
func (*SummaryReply) Descriptor() ([]byte, []int) {
	return file_beef_beef_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryReply) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_beef_beef_proto protoreflect.FileDescriptor

var file_beef_beef_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x65, 0x65, 0x66, 0x2f, 0x62, 0x65, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x62, 0x65, 0x65, 0x66, 0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x32, 0x3d, 0x0a, 0x04, 0x42, 0x65, 0x65, 0x66, 0x12,
	0x35, 0x0a, 0x07, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x14, 0x2e, 0x62, 0x65, 0x65,
	0x66, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x62, 0x65, 0x65, 0x66, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x62, 0x65, 0x33, 0x2f, 0x62, 0x65,
	0x65, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beef_beef_proto_rawDescOnce sync.Once
	file_beef_beef_proto_rawDescData = file_beef_beef_proto_rawDesc
)

func file_beef_beef_proto_rawDescGZIP() []byte {
	file_beef_beef_proto_rawDescOnce.Do(func() {
		file_beef_beef_proto_rawDescData = protoimpl.X.CompressGZIP(file_beef_beef_proto_rawDescData)
	})
	return file_beef_beef_proto_rawDescData
}

var file_beef_beef_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_beef_beef_proto_goTypes = []any{
	(*SummaryRequest)(nil), // 0: beef.SummaryRequest
	(*SummaryReply)(nil),   // 1: beef.SummaryReply
}
var file_beef_beef_proto_depIdxs = []int32{
	0, // 0: beef.Beef.Summary:input_type -> beef.SummaryRequest
	1, // 1: beef.Beef.Summary:output_type -> beef.SummaryReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_beef_beef_proto_init() }
func file_beef_beef_proto_init() {
	if File_beef_beef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beef_beef_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beef_beef_proto_goTypes,
		DependencyIndexes: file_beef_beef_proto_depIdxs,
		MessageInfos:      file_beef_beef_proto_msgTypes,
	}.Build()
	File_beef_beef_proto = out.File
	file_beef_beef_proto_rawDesc = nil
	file_beef_beef_proto_goTypes = nil
	file_beef_beef_proto_depIdxs = nil
}
